changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - github-actions
  categories:
    - title: Neue Funktionen
      labels:
        - enhancement
        - feature
    - title: Fehlerbehebungen
      labels:
        - bug
        - fix
    - title: Dokumentation
      labels:
        - documentation
        - docs
    - title: Wartung
      labels:
        - maintenance
        - chore
    - title: Weitere Änderungen
      labels:
        - "*"
